#sudo: required

services:
  - docker

before_install:
  - docker build -t thehinneh/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true thehinneh/docker-react npm run test -- --coverage
