#sudo: required

services:
  - docker

before_install:
  - docker build -t thehinneh/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true thehinneh/docker-react npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "docker-react"
  env: "Dockerreact-env"
  bucket_name: "docker-react"
#  bucket_name: "elasticbeanstalk-us-east-1-354991975663"

  on:
    branch: main

  access_key_id:
    secure: "$AWS_ACCESS_KEY_ID"
  secret_access_key:
    secure: "$AWS_SECRET_ACCESS_KEY"
